=== BLaurent/predix-starter/asset-setup/json/engines-schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "uri",
      "type",
      "horsepower",
      "stroke",
      "bore",
      "RPM",
      "manufacturer"
    ],
    "properties": {
      "uri": {
        "type": "string",
        "minLength": 1
      },
      "type": {
        "type": "string",
        "minLength": 1
      },
      "horsepower": {
        "type": "string",
        "minLength": 1
      },
      "stroke": {
        "type": "string",
        "minLength": 1
      },
      "bore": {
        "type": "string",
        "minLength": 1
      },
      "RPM": {
        "type": "string",
        "minLength": 1
      },
      "manufacturer": {
        "type": "string",
        "minLength": 1
      }
    }
  }
}

=== BLaurent/predix-starter/asset-setup/json/engines.json
[
  {
    "uri": "/engines/v12-1",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-2",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-3",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-4",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-5",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-6",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-7",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-8",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-9",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-10",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-11",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-12",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-13",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-14",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-15",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-16",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-17",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-18",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v12-19",
    "type": "7FDL",
    "horsepower": "4400",
    "stroke": "230",
    "bore": "220",
    "RPM": "2400",
    "manufacturer": "/manufacturers/GE"
  },

  {
    "uri": "/engines/v16-1",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-2",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-3",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-4",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-5",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-6",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-7",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-8",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-9",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-10",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-11",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-12",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-13",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-14",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-15",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-16",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-17",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-18",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },
  {
    "uri": "/engines/v16-19",
    "type": "7FD",
    "horsepower": "4400",
    "stroke": "210",
    "bore": "220",
    "RPM": "900",
    "manufacturer": "/manufacturers/GE"
  },

  {
    "uri": "/engines/v16-2-1",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-2",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-3",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-4",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-5",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-6",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-7",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-8",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-9",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-10",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-11",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-12",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },
  {
    "uri": "/engines/v16-2-13",
    "type": "710",
    "horsepower": "4300",
    "stroke": "250",
    "bore": "200",
    "RPM": "215",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },

  {
    "uri": "/engines/645",
    "type": "7FDL",
    "horsepower": "1500",
    "stroke": "190",
    "bore": "230",
    "RPM": "900",
    "manufacturer": "/manufacturers/electro-motive-diesel"
  },

  {
    "uri": "/engines/QSK19-1",
    "type": "Diesel",
    "horsepower": "2100",
    "stroke": "159",
    "bore": "159",
    "RPM": "800",
    "manufacturer": "/manufacturers/cummins"
  },
  {
    "uri": "/engines/QSK19-2",
