=== BLaurent/predix-starter/asset-setup/json/manufacturers-schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "uri",
      "name",
      "year_founded",
      "hqLatLng"
    ],
    "properties": {
      "uri": {
        "type": "string",
        "minLength": 1
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "year_founded": {
        "type": "string",
        "minLength": 1
      },
      "hqLatLng": {
        "type": "object",
        "properties": {
          "lat": {
            "type": "number"
          },
          "lng": {
            "type": "number"
          }
        },
        "required": [
          "lat",
          "lng"
        ]
      }
    }
  }
}

=== BLaurent/predix-starter/asset-setup/json/manufacturers.json
[
  { "uri": "/manufacturers/GE",
    "name": "General Electric Transportation",
    "year_founded": "1892" ,
    "hqLatLng":{"lat": 41.881138, "lng": -87.640666 }
  },

  {"uri": "/manufacturers/electro-motive-diesel",
    "name": "Electro-Motive Diesel",
    "year_founded": "1922",
    "hqLatLng": {"lat": 41.798091, "lng": -87.849247}
  },

  {"uri": "/manufacturers/national-railway-equipment",
    "name": "National Railway Equipment",
    "year_founded": "1984",
    "hqLatLng": {"lat": 41.515181 , "lng":-90.411707 }
  },

  {"uri": "/manufacturers/cummins",
    "name": "Cummins",
    "year_founded": "1919",
    "hqLatLng": {"lat":39.204000, "lng": -85.922910}
  }
]
